export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const COMPARE_PRODUCT = "COMPARE_PRODUCT";
export const SAVE_NP_GUESSES = "SAVE_NP_GUESSES";
export const SAVE_IMAGE_HASH = "SAVE_IMAGE_HASH";
export const SAVE_DIFFICULTY = "SAVE_DIFFICULTY";
export const SAVE_NATIONAL_PARKS = "SAVE_NATIONAL_PARKS";
